version: '3'

services:
  api:
    build: .
    restart: always
    networks:
      - web
    expose:
      - "5000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:api.assignpro.ml"
      - "traefik.port=5000"
      - "traefik.protocol=http"

networks:
  web:
    external: true
